name: Minecraft_24-7_Final

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Java 26
        uses: actions/setup-java@v4
        with:
          java-version: '26'
          distribution: 'oracle'
      - name: Python Libs
        run: pip install requests
      - name: Playit
        run: |
          curl -SsL -o playit https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-linux-amd64
          chmod +x playit
      - name: Download Server
        run: |
          python3 -c '
          import requests
          m = requests.get("https://launchermeta.mojang.com/mc/game/version_manifest.json").json()
          url = requests.get(next(v["url"] for v in m["versions"] if v["id"] == m["latest"]["release"])).json()["downloads"]["server"]["url"]
          with open("server.jar", "wb") as f: f.write(requests.get(url).content)
          '
      - name: Run
        env:
          PLAYIT_SECRET: ${{ secrets.PLAYIT_SECRET }}
        run: |
          # playitのログを表示するように変更
          ./playit --secret "$PLAYIT_SECRET" & 
          python3 -u server.py --headless
